# gcloud-sqlproxy:
#   serviceAccount:
#     annotations:
#       iam.gke.io/gcp-service-account: 'matrix-admin-bot@parity-prod.iam.gserviceaccount.com'
#   cloudsql:
#     instances:
#     - instance: "matrix-admin-bot-db-pgsql"
#       project: "parity-prod"
#       region: "europe-west3"
#       port: 5432

common:
  env:
    APP_HOST: "https://matrix-admin-bot.parity-prod.parity.io"
    DATABASE_NAME: "matrix-admin-bot"
    MATRIX_SERVER_URL: "https://m.parity.io"
    MATRIX_SERVER_DOMAIN: "parity.io"
  secrets:
    ACCESS_TOKEN: ref+vault://kv/cicd/gitlab/parity/mirrors/matrix-admin-bot/parity-prod#ACCESS_TOKEN
    INVITE_ROOMS_LIST: ref+vault://kv/cicd/gitlab/parity/mirrors/matrix-admin-bot/parity-prod#INVITE_ROOMS_LIST
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target: traefik-internal.parity-prod.parity.io.
    rules:
    - host: matrix-admin-bot.parity-prod.parity.io
      http:
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: matrix-admin-bot
              port:
                name: http
    tls:
    - hosts:
      - matrix-admin-bot.parity-prod.parity.io
      secretName: matrix-admin-bot.parity-prod.parity.io
