# gcloud-sqlproxy:
#   serviceAccountName: "matrix-admin-bot"
#   serviceAccount:
#     create: true
#     name: matrix-admin-bot
#   networkPolicy:
#     enabled: false

common:
  fullnameOverride: "matrix-admin-bot"
  extraLabels:
    team: "bizautomation"
  serviceAccount:
    create: false
  image:
    repository: paritytech/matrix-admin-bot
  envFrom:
    - secretRef:
        name: matrix-admin-bot
  service:
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  ingress:
    enabled: false
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns01
      kubernetes.io/ingress.class: traefik-internal
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
  # Enable after endpoint is created
  # livenessProbe:
  #   httpGet:
  #     path: /health
  #     port: 8000
  #     scheme: HTTP
  # readinessProbe:
  #   httpGet:
  #     path: /health
  #     port: 8000
  #     scheme: HTTP
