name: Publish and deploy

on:
  push:
    branches:
      - master
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  APP: "matrix-admin-bot"

jobs:
  build_push_docker:
    name: Build docker image
    runs-on: ubuntu-latest
    environment: master_n_tags
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Generate vars
        id: vars
        run: |
          echo "DATE_TAG=$(date -u +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
          echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            docker.io/paritytech/matrix-admin-bot:${{ steps.vars.outputs.DATE_TAG }}-${{ steps.vars.outputs.SHORT_SHA }}
