name: Build image

on:
  push:
    branches:
      - master
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

#to use reusable workflow
permissions:
  id-token: write
  contents: read

jobs:
  build-manifest:
    name: build images from manifest
    uses: paritytech/ci-actions/.github/workflows/build-manifest.yaml@main
    permissions:
      id-token: write
      contents: write
    with:
      push: ${{ github.event_name == 'push' }}
      environment: ${{ github.event_name == 'push' && 'docker-publish' || null }}
      registry: europe-docker.pkg.dev/parity-mgmt/matrix-admin-bot
      images: |
        matrix-admin-bot:
          dockerfile: ./Dockerfile
    secrets:
      GCP_SA_GITHUB: ${{ secrets.GCP_SA_GITHUB }}
      GCP_WIP_GITHUB: ${{ secrets.GCP_WIP_GITHUB }}
